version: 0.1

phases:
  install:
    commands:
      - echo Installing rdk...
      - pip install .
  pre_build:
    commands:
      - echo Starting tests
      - rdk init
  build:
    commands:
      - rdk create LP3-TestRule-P3 --runtime python3.6 --resource-types AWS::EC2::SecurityGroup
      - sleep 5
      - rdk create LP3-TestRule-P2 --runtime python2.7 --resource-types AWS::EC2::SecurityGroup
      - sleep 5
      - rdk create LP3-TestRule-JS --runtime nodejs4.3 --resource-types AWS::EC2::SecurityGroup
      - sleep 5
      - rdk modify LP3-TestRule-P3 --input-parameters '{"TestParameter":"TestValue"}'
      - sleep 5
      - rdk create LP3-TestRule-P3-Periodic --runtime python3.6 --maximum-frequency One_Hour
      - rdk test-local --all
      - rdk deploy --all
      - sleep 30
      - rdk logs LP3-TestRule-P3
  post_build:
    commands:
      - echo Build completed on `date`
